### ISSUE TITLE
README.md inconsistent sample

### ISSUE THREAD

**Issue by miltongq** [symphonyoss/JCurl#2]
On "Script usage" section, missing the "eval" keyword at "# Add user to room" sample.

**Comment by ldrozdz** [comment]
Actually we don't need `eval` there. It is only needed when we extract a value from the response and want to save it to a Bash variable.

This actually means that `eval` is also unnecessary in the following example (sending a message). I'll remove it from the doc.

**Comment by ldrozdz** [comment]
Fixed in 0.9.6.
