### ISSUE TITLE
Add a homebrew target for easy install on macs

### ISSUE THREAD

**Issue by ldrozdz** [symphonyoss/JCurl#24]

**Comment by yschimke** [comment]
https://github.com/symphonyoss/JCurl/pull/22

Ideally this would live at https://github.com/symphonyoss/homebrew-tap/jcurl.rb but I can't submit a PR to that location

With that structure it would be installable via

brew install symphonyoss/tap/jcurl

To test current file use brew install jcurl.rb

**Comment by ldrozdz** [comment]
Fixed in 6cb25515c122abd8c500a24ce0510247279d9166
